language: node_js
node_js:
  - "6.0"
  - "7.0"
  - "stable"
  - "node"
before_install:
script: "npm run-script test-travis"
# Send coverage data to Coveralls
before_script:
after_script: "npm run-script coverall"
